countries = [
    {"code": 'BY', "name": "Беларусь", "aliases": ["belarus", "белорусь", "белоруссия", "республика беларусь"]},
    {"code": 'RU', "name": "Россия", "aliases": ["russia", "российская федерация"]},
    {"code": 'UA', "name": "Украина", "aliases": ["ukraine"]},

    {"code": 'US', "name": "США", "aliases": ["usa", "america", "united states", "united states of america","сша", "америка", "соединенные штаты", "соединенные штаты америки"]},
    {"code": 'CN', "name": "Китай", "aliases": ["china"]},

    {"code": "AU", "name": "Австралия", "aliases": ["australia"]},
    {"code": "AT", "name": "Австрия", "aliases": ["austria"]},
    {"code": "AZ", "name": "Азербайджан", "aliases": ["azerbaijan"]},
    {"code": "AR", "name": "Аргентина", "aliases": ["argentina"]},
    {"code": "AM", "name": "Армения", "aliases": ["armenia"]},
    {"code": "AF", "name": "Афганистан", "aliases": ["afghanistan"]},
    {"code": "BE", "name": "Бельгия", "aliases": ["belgium"]},
    {"code": "BG", "name": "Болгария", "aliases": ["bulgaria"]},
    {"code": "BR", "name": "Бразилия", "aliases": ["brazil"]},
    {"code": "VA", "name": "Ватикан", "aliases": ["vatican"]},
    {"code": "GB", "name": "Великобритания", "aliases": ["great britain", "britan", "england", "британия", "англия", "соединенное королевство"]},
    {"code": "VE", "name": "Венесуэла", "aliases": ["venezuela"]},
    {"code": "VN", "name": "Вьетнам", "aliases": ["vietnam"]},
    {"code": "DE", "name": "Германия", "aliases": ["germany"]},
    {"code": "HK", "name": "Гонконг", "aliases": ["hong kong"]},
    {"code": "GL", "name": "Гренландия", "aliases": ["greenland"]},
    {"code": "GR", "name": "Греция", "aliases": ["greece"]},
    {"code": "GE", "name": "Грузия", "aliases": ["georgia"]},
    {"code": "DK", "name": "Дания", "aliases": ["denmark"]},
    {"code": "EG", "name": "Египет", "aliases": ["egypt"]},
    {"code": "IL", "name": "Израиль", "aliases": ["israel"]},
    {"code": "IN", "name": "Индия", "aliases": ["india"]},
    {"code": "ID", "name": "Индонезия", "aliases": ["indonesia"]},
    {"code": "JO", "name": "Иордания", "aliases": ["jordan"]},
    {"code": "IQ", "name": "Ирак", "aliases": ["iraq"]},
    {"code": "IR", "name": "Иран", "aliases": ["iran"]},
    {"code": "IE", "name": "Ирландия", "aliases": ["ireland"]},
    {"code": "IS", "name": "Исландия", "aliases": ["iceland"]},
    {"code": "ES", "name": "Испания", "aliases": ["spain"]},
    {"code": "IT", "name": "Италия", "aliases": ["italy"]},
    {"code": "YE", "name": "Йемен", "aliases": ["yemen"]},
    {"code": "KZ", "name": "Казахстан", "aliases": ["kazakhstan"]},
    {"code": "CA", "name": "Канада", "aliases": ["canada"]},
    {"code": "QA", "name": "Катар", "aliases": ["quatar"]},
    {"code": "CY", "name": "Кипр", "aliases": ["cyprus"]},
    {"code": "KG", "name": "Кыргызстан", "aliases": ["kyrgyzstan", "киргизия", "Киргиизская Республика"]},
    {"code": "KP", "name": "КНДР", "aliases": ["north korea", "северная корея"]},
    {"code": "KR", "name": "Корея", "aliases": ["korea", "южная корея"]},
    {"code": "CU", "name": "Куба", "aliases": ["cuba"]},
    {"code": "KW", "name": "Кувейт", "aliases": ["kuwait"]},
    {"code": "LV", "name": "Латвия", "aliases": ["latvia"]},
    {"code": "LY", "name": "Ливия", "aliases": ["libya"]},
    {"code": "LT", "name": "Литва", "aliases": ["lithuania"]},
    {"code": "LI", "name": "Лихтенштейн", "aliases": ["liechtenstein"]},
    {"code": "LU", "name": "Люксембург", "aliases": ["luxembourg"]},
    {"code": "MK", "name": "Македония", "aliases": ["macedonia"]},
    {"code": "MX", "name": "Мексика", "aliases": ["mexico"]},
    {"code": "MD", "name": "Молдова", "aliases": ["moldova", "молдавия"]},
    {"code": "MN", "name": "Монголия", "aliases": ["mongolia"]},
    {"code": "NL", "name": "Нидерланды", "aliases": ["netherlands", "голландия"]},
    {"code": "NO", "name": "Норвегия", "aliases": ["norway"]},
    {"code": "AE", "name": "ОАЭ", "aliases": ["united arab emirates", "эмираты", "арабские эмираты", "объединенные арабские эмираты"]},
    {"code": "PK", "name": "Пакистан", "aliases": ["pakistan"]},
    {"code": "PS", "name": "Палестина", "aliases": ["palestinian"]},
    {"code": "PE", "name": "Перу", "aliases": ["peru"]},
    {"code": "PL", "name": "Польша", "aliases": ["poland"]},
    {"code": "PT", "name": "Португалия", "aliases": ["portugal"]},
    {"code": "RO", "name": "Румыния", "aliases": ["romania"]},
    {"code": "SA", "name": "Саудовская Аравия", "aliases": ["saudi arabia"]},
    {"code": "RS", "name": "Сербия", "aliases": ["serbia"]},
    {"code": "SG", "name": "Сингапур", "aliases": ["singapore"]},
    {"code": "SY", "name": "Сирия", "aliases": ["syria"]},
    {"code": "SK", "name": "Словакия", "aliases": ["slovakia"]},
    {"code": "SI", "name": "Словения", "aliases": ["slovenia"]},
    {"code": "SO", "name": "Сомали", "aliases": ["somalia"]},
    {"code": "SD", "name": "Судан", "aliases": ["sudan"]},
    {"code": "TJ", "name": "Таджикистан", "aliases": ["tajikistan"]},
    {"code": "TH", "name": "Таиланд", "aliases": ["thailand"]},
    {"code": "TW", "name": "Тайвань", "aliases": ["taiwan"]},
    {"code": "TZ", "name": "Танзания", "aliases": ["tanzania"]},
    {"code": "TN", "name": "Тунис", "aliases": ["tunisia"]},
    {"code": "TM", "name": "Туркменистан", "aliases": ["turkmenistan", "туркмения"]},
    {"code": "TR", "name": "Турция", "aliases": ["turkey"]},
    {"code": "UZ", "name": "Узбекистан", "aliases": ["uzbekistan"]},
    {"code": "FI", "name": "Финляндия", "aliases": ["finland"]},
    {"code": "FR", "name": "Франция", "aliases": ["france"]},
    {"code": "HR", "name": "Хорватия", "aliases": ["croatia"]},
    {"code": "ME", "name": "Черногория", "aliases": ["montenegro"]},
    {"code": "CZ", "name": "Чехия", "aliases": ["czechia"]},
    {"code": "CL", "name": "Чили", "aliases": ["chile"]},
    {"code": "CH", "name": "Швейцария", "aliases": ["switzerland"]},
    {"code": "SE", "name": "Швеция", "aliases": ["sweden"]},
    {"code": "EE", "name": "Эстония", "aliases": ["estonia"]},
    {"code": "ZA", "name": "ЮАР", "aliases": ["republic of south africa", "south africa", "южно-африканская республика", "южная южно-африканская"]},
    {"code": "JM", "name": "Ямайка", "aliases": ["jamaica"]},
    {"code": "JPN", "name": "Япония", "aliases": ["japan"]},
    {"code": 'JP', "name": "Япония", "aliases": ["japan"]}
]