countries = [
    {"code": 'BY', "name": "Беларусь", "aliases": ["belarus", "белорусь", "белоруссия", "республика беларусь"]},
    {"code": 'RU', "name": "Россия", "aliases": ["russia", "российская федерация"]},
    {"code": 'UA', "name": "Украина", "aliases": ["ukraine"]},
    {"code": "AU", "name": "Австралия", "aliases": ["australia"]},
    {"code": "AT", "name": "Австрия", "aliases": ["austria"]},
    {"code": "AZ", "name": "Азербайджан", "aliases": ["azerbaijan"]},
    {"code": "AL", "name": "Албания", "aliases": ["albania"]},
    {"code": "DZ", "name": "Алжир", "aliases": ["algeria"]},
    {"code": "VI", "name": "Виргинские острова", "aliases": ["united states virgin islands", "virgin islands", "американские виргинские острова", "виргинские острова"]},
    {"code": "AS", "name": "Американское Самоа", "aliases": ["american samoa", "samoa"]},
    {"code": "AI", "name": "Ангилья", "aliases": ["anguilla"]},
    {"code": "AO", "name": "Ангола", "aliases": ["angola"]},
    {"code": "AD", "name": "Андорра", "aliases": ["andorra"]},
    {"code": "AQ", "name": "Антарктида", "aliases": ["antarctica"]},
    {"code": "AG", "name": "Антигуа и Барбуда", "aliases": ["antigua and barbuda", "антигуа", "барбуда"]},
    {"code": "AR", "name": "Аргентина", "aliases": ["argentina"]},
    {"code": "AM", "name": "Армения", "aliases": ["armenia"]},
    {"code": "AW", "name": "Аруба", "aliases": ["aruba"]},
    {"code": "AF", "name": "Афганистан", "aliases": ["afghanistan"]},
    {"code": "BS", "name": "Багамские острова", "aliases": ["bahamas", "багамы"]},
    {"code": "BD", "name": "Бангладеш", "aliases": ["bangladesh"]},
    {"code": "BB", "name": "Барбадос", "aliases": ["barbados"]},
    {"code": "BH", "name": "Бахрейн", "aliases": ["bahrain"]},
    {"code": "BZ", "name": "Белиз", "aliases": ["belize"]},
    {"code": "BE", "name": "Бельгия", "aliases": ["belgium"]},
    {"code": "BJ", "name": "Бенин", "aliases": ["benin"]},
    {"code": "BM", "name": "Бермуды", "aliases": ["bermuda"]},
    {"code": "BG", "name": "Болгария", "aliases": ["bulgaria"]},
    {"code": "BO", "name": "Боливия", "aliases": ["bolivia"]},
    {"code": "BQ", "name": "Бонайре, Синт-Эстатиус и Саба", "aliases": ["caribbean netherlands", "бонайре", "синт-эстатиус", "саба"]},
    {"code": "BA", "name": "Босния и Герцеговина", "aliases": ["bosnia and herzegovina", "босния"]},
    {"code": "BW", "name": "Ботсвана", "aliases": ["botswana"]},
    {"code": "BR", "name": "Бразилия", "aliases": ["brazil"]},
    {"code": "IO", "name": "Британская территория в Индийском океане", "aliases": ["british indian ocean territory"]},
    {"code": "VG", "name": "Британские Виргинские острова", "aliases": ["british virgin islands", "virgin islands", "виргинские острова"]},
    {"code": "BN", "name": "Бруней", "aliases": ["brunei darussalam", "brunei"]},
    {"code": "BV", "name": "Буве", "aliases": ["bouvet island", "bouvet"]},
    {"code": "BF", "name": "Буркина-Фасо", "aliases": ["burkina faso", "burkina-faso", "буркина фасо"]},
    {"code": "BI", "name": "Бурунди", "aliases": ["burundi"]},
    {"code": "BT", "name": "Бутан", "aliases": ["bhutan"]},
    {"code": "VU", "name": "Вануату", "aliases": ["vanuatu"]},
    {"code": "VA", "name": "Ватикан", "aliases": ["vatican"]},
    {"code": "GB", "name": "Великобритания", "aliases": ["uk", "great britain", "britan", "england", "британия", "англия", "соединенное королевство"]},
    {"code": "HU", "name": "Венгрия", "aliases": ["hungary"]},
    {"code": "VE", "name": "Венесуэла", "aliases": ["venezuela"]},
    {"code": "TL", "name": "Восточный Тимор", "aliases": ["east timor", "timor", "", "восточный тимор", "тимор-лешти", "тимор лешти"]},
    {"code": "VN", "name": "Вьетнам", "aliases": ["vietnam"]},
    {"code": "GA", "name": "Габон", "aliases": ["gabon"]},
    {"code": "HT", "name": "Гаити", "aliases": ["haiti"]},
    {"code": "GY", "name": "Гайана", "aliases": ["guyana"]},
    {"code": "GM", "name": "Гамбия", "aliases": ["gambia"]},
    {"code": "GH", "name": "Гана", "aliases": ["ghana"]},
    {"code": "GP", "name": "Гваделупа", "aliases": ["guadeloupe"]},
    {"code": "GT", "name": "Гватемала", "aliases": ["guatemala"]},
    {"code": "GN", "name": "Гвинея", "aliases": ["guinea"]},
    {"code": "GW", "name": "Гвинея-Бисау", "aliases": ["guinea-bissau"]},
    {"code": "DE", "name": "Германия", "aliases": ["germany"]},
    {"code": "GG", "name": "Гернси", "aliases": ["guernsey"]},
    {"code": "GI", "name": "Гибралтар", "aliases": ["gibraltar"]},
    {"code": "HN", "name": "Гондурас", "aliases": ["honduras"]},
    {"code": "HK", "name": "Гонконг", "aliases": ["hong kong"]},
    {"code": "GD", "name": "Гренада", "aliases": ["grenada"]},
    {"code": "GL", "name": "Гренландия", "aliases": ["greenland"]},
    {"code": "GR", "name": "Греция", "aliases": ["greece"]},
    {"code": "GE", "name": "Грузия", "aliases": ["georgia"]},
    {"code": "GU", "name": "Гуам", "aliases": ["guam"]},
    {"code": "DK", "name": "Дания", "aliases": ["denmark"]},
    {"code": "CD", "name": "Демократическая Республика Конго", "aliases": ["democratic republic of the congo"]},
    {"code": "JE", "name": "Джерси", "aliases": ["jersey"]},
    {"code": "DJ", "name": "Джибути", "aliases": ["djibouti"]},
    {"code": "DM", "name": "Доминика", "aliases": ["dominica"]},
    {"code": "DO", "name": "Доминикана", "aliases": ["dominican republic"]},
    {"code": "EG", "name": "Египет", "aliases": ["egypt"]},
    {"code": "ZM", "name": "Замбия", "aliases": ["zambia"]},
    {"code": "EH", "name": "Западная Сахара", "aliases": ["western sahara", "sahara", "сахара", "сахарская республика", "сахарская арабская республика", "сахарская демократическая республика", "сахарская арабская демократическая республика"]},
    {"code": "ZW", "name": "Зимбабве", "aliases": ["zimbabwe"]},
    {"code": "IL", "name": "Израиль", "aliases": ["israel"]},
    {"code": "IN", "name": "Индия", "aliases": ["india"]},
    {"code": "ID", "name": "Индонезия", "aliases": ["indonesia"]},
    {"code": "JO", "name": "Иордания", "aliases": ["jordan"]},
    {"code": "IQ", "name": "Ирак", "aliases": ["iraq"]},
    {"code": "IR", "name": "Иран", "aliases": ["iran"]},
    {"code": "IE", "name": "Ирландия", "aliases": ["ireland"]},
    {"code": "IS", "name": "Исландия", "aliases": ["iceland"]},
    {"code": "ES", "name": "Испания", "aliases": ["spain"]},
    {"code": "IT", "name": "Италия", "aliases": ["italy"]},
    {"code": "YE", "name": "Йемен", "aliases": ["yemen"]},
    {"code": "CV", "name": "Кабо-Верде", "aliases": ["cape verde", "кабо-верде", "кабо верде", "острова зеленого мыса"]},
    {"code": "KZ", "name": "Казахстан", "aliases": ["kazakhstan"]},
    {"code": "KY", "name": "Каймановы острова", "aliases": ["cayman islands"]},
    {"code": "KH", "name": "Камбоджа", "aliases": ["cambodia"]},
    {"code": "CM", "name": "Камерун", "aliases": ["cameroon"]},
    {"code": "CA", "name": "Канада", "aliases": ["canada"]},
    {"code": "QA", "name": "Катар", "aliases": ["quatar"]},
    {"code": "KE", "name": "Кения", "aliases": ["kenya"]},
    {"code": "CY", "name": "Кипр", "aliases": ["cyprus"]},
    {"code": "KG", "name": "Кыргызстан", "aliases": ["kyrgyzstan", "киргизия", "киргиизская республика"]},
    {"code": "KI", "name": "Кирибати", "aliases": ["kiribati"]},
    {"code": 'CN', "name": "Китай", "aliases": ["china"]},
    {"code": "KP", "name": "КНДР", "aliases": ["north korea", "северная корея"]},
    {"code": "CC", "name": "Кокосовые острова", "aliases": ["cocos islands", "keeling", "килинг"]},
    {"code": "CO", "name": "Колумбия", "aliases": ["colombia"]},
    {"code": "KM", "name": "Коморские острова", "aliases": ["comoros"]},
    {"code": "KR", "name": "Корея", "aliases": ["korea"]},
    {"code": "CR", "name": "Коста-Рика", "aliases": ["costa rica", "коста рика"]},
    {"code": "CI", "name": "Кот-д’Ивуар", "aliases": ["cote d'ivoire", "cote d ivoire", "cote divoire", "ivory coast", "кот-д'ивуар", "кот д ивуар", "кот дивуар", "кот-дивуар", "берег слоновой кости"]},
    {"code": "CU", "name": "Куба", "aliases": ["cuba"]},
    {"code": "KW", "name": "Кувейт", "aliases": ["kuwait"]},
    {"code": "CW", "name": "Кюрасао", "aliases": ["curacao"]},
    {"code": "LA", "name": "Лаос", "aliases": ["laos"]},
    {"code": "LV", "name": "Латвия", "aliases": ["latvia"]},
    {"code": "LS", "name": "Лесото", "aliases": ["lesotho"]},
    {"code": "LR", "name": "Либерия", "aliases": ["liberia"]},
    {"code": "LB", "name": "Ливан", "aliases": ["lebanon"]},
    {"code": "LY", "name": "Ливия", "aliases": ["libya"]},
    {"code": "LT", "name": "Литва", "aliases": ["lithuania"]},
    {"code": "LI", "name": "Лихтенштейн", "aliases": ["liechtenstein"]},
    {"code": "LU", "name": "Люксембург", "aliases": ["luxembourg"]},
    {"code": "MU", "name": "Маврикий", "aliases": ["mauritius"]},
    {"code": "MR", "name": "Мавритания", "aliases": ["mauritania"]},
    {"code": "MG", "name": "Мадагаскар", "aliases": ["madagascar"]},
    {"code": "YT", "name": "Майотта", "aliases": ["mayotte"]},
    {"code": "MO", "name": "Макао (Аомынь)", "aliases": ["macau", "макао", "аомынь"]},
    {"code": "MK", "name": "Македония", "aliases": ["macedonia"]},
    {"code": "MW", "name": "Малави", "aliases": ["malawi"]},
    {"code": "MY", "name": "Малайзия", "aliases": ["malaysia"]},
    {"code": "ML", "name": "Мали", "aliases": ["mali"]},
    {"code": "MV", "name": "Мальдивы", "aliases": ["maldives"]},
    {"code": "MT", "name": "Мальта", "aliases": ["malta"]},
    {"code": "MA", "name": "Марокко", "aliases": ["morocco"]},
    {"code": "MQ", "name": "Мартиника", "aliases": ["martinique"]},
    {"code": "MH", "name": "Маршалловы острова", "aliases": ["marshall islands"]},
    {"code": "MX", "name": "Мексика", "aliases": ["mexico"]},
    {"code": "MZ", "name": "Мозамбик", "aliases": ["mozambique"]},
    {"code": "MD", "name": "Молдова", "aliases": ["moldova", "молдавия"]},
    {"code": "MC", "name": "Монако", "aliases": ["monaco"]},
    {"code": "MN", "name": "Монголия", "aliases": ["mongolia"]},
    {"code": "MS", "name": "Монтсеррат", "aliases": ["montserrat"]},
    {"code": "MM", "name": "Мьянма (Бирма)", "aliases": ["myanmar (burma)"]},
    {"code": "NA", "name": "Намибия", "aliases": ["namibia"]},
    {"code": "NR", "name": "Науру", "aliases": ["nauru"]},
    {"code": "NP", "name": "Непал", "aliases": ["nepal"]},
    {"code": "NE", "name": "Нигер", "aliases": ["niger"]},
    {"code": "NG", "name": "Нигерия", "aliases": ["nigeria"]},
    {"code": "AN", "name": "Нидерландские Антильские острова", "aliases": ["netherlands antilles"]},
    {"code": "NL", "name": "Нидерланды", "aliases": ["netherlands", "голландия"]},
    {"code": "NI", "name": "Никарагуа", "aliases": ["nicaragua"]},
    {"code": "NU", "name": "Ниуэ", "aliases": ["niue"]},
    {"code": "NZ", "name": "Новая Зеландия", "aliases": ["new zealand"]},
    {"code": "NC", "name": "Новая Каледония", "aliases": ["new caledonia"]},
    {"code": "NO", "name": "Норвегия", "aliases": ["norway"]},
    {"code": "AE", "name": "ОАЭ", "aliases": ["united arab emirates", "эмираты", "арабские эмираты", "объединенные арабские эмираты"]},
    {"code": "OM", "name": "Оман", "aliases": ["oman"]},
    {"code": "NF", "name": "Остров Норфолк", "aliases": ["norfolk island", "norfolk", "норфолк"]},
    {"code": "CX", "name": "Остров Рождества", "aliases": ["christmas island"]},
    {"code": "SH", "name": "Остров Святой Елены", "aliases": ["saint helena"]},
    {"code": "HM", "name": "Остров Херд и острова Макдональд", "aliases": ["heard island and mcdonald islands"]},
    {"code": "CK", "name": "Острова Кука", "aliases": ["cook islands"]},
    {"code": "PN", "name": "Острова Питкэрн", "aliases": ["pitcairn islands"]},
    {"code": "TC", "name": "Острова Тёркс и Кайкос", "aliases": ["the turks and caicos islands"]},
    {"code": "WF", "name": "Острова Уоллис и Футуна", "aliases": ["wallis and futuna"]},
    {"code": "PK", "name": "Пакистан", "aliases": ["pakistan"]},
    {"code": "PW", "name": "Палау", "aliases": ["palau"]},
    {"code": "PS", "name": "Палестина", "aliases": ["palestinian", "palestina"]},
    {"code": "PA", "name": "Панама", "aliases": ["panama"]},
    {"code": "PG", "name": "Папуа Новая Гвинея", "aliases": ["papua new guinea", "papua", "new guinea", "папуа", "новая гвинея"]},
    {"code": "PY", "name": "Парагвай", "aliases": ["paraguay"]},
    {"code": "PE", "name": "Перу", "aliases": ["peru"]},
    {"code": "PL", "name": "Польша", "aliases": ["poland"]},
    {"code": "PT", "name": "Португалия", "aliases": ["portugal"]},
    {"code": "PR", "name": "Пуэрто-Рико", "aliases": ["puerto rico", "пуэрто рико"]},
    {"code": "CG", "name": "Республика Конго", "aliases": ["republic of the congo", "congo", "конго"]},
    {"code": "RE", "name": "Реюньон", "aliases": ["reunion"]},
    {"code": "RW", "name": "Руанда", "aliases": ["rwanda"]},
    {"code": "RO", "name": "Румыния", "aliases": ["romania"]},
    {"code": "SV", "name": "Сальвадор", "aliases": ["el salvador"]},
    {"code": "WS", "name": "Самоа", "aliases": ["samoa"]},
    {"code": "SM", "name": "Сан-Марино", "aliases": ["san marino", "сан марино"]},
    {"code": "ST", "name": "Сан-Томе и Принсипи", "aliases": ["sao tome and principe", "sao tome", "principe", "сан томе и принсипи", "сан-томе", "сан томе", "принсипи"]},
    {"code": "SA", "name": "Саудовская Аравия", "aliases": ["saudi arabia"]},
    {"code": "MP", "name": "Северные Марианские острова", "aliases": ["northern mariana islands"]},
    {"code": "SC", "name": "Сейшелы", "aliases": ["seychelles"]},
    {"code": "PM", "name": "Сен-Пьер и Микелон", "aliases": ["saint-pierre and miquelon"]},
    {"code": "SN", "name": "Сенегал", "aliases": ["senegal"]},
    {"code": "VC", "name": "Сент-Винсент и Гренадины", "aliases": ["saint vincent and the grenadines"]},
    {"code": "KN", "name": "Сент-Китс и Невис", "aliases": ["saint kitts and nevis"]},
    {"code": "LC", "name": "Сент-Люсия", "aliases": ["saint lucia"]},
    {"code": "RS", "name": "Сербия", "aliases": ["serbia"]},
    {"code": "SG", "name": "Сингапур", "aliases": ["singapore"]},
    {"code": "SY", "name": "Сирия", "aliases": ["syria"]},
    {"code": "SK", "name": "Словакия", "aliases": ["slovakia"]},
    {"code": "SI", "name": "Словения", "aliases": ["slovenia"]},
    {"code": "SB", "name": "Соломоновы острова", "aliases": ["solomon islands"]},
    {"code": "SO", "name": "Сомали", "aliases": ["somalia"]},
    {"code": "SD", "name": "Судан", "aliases": ["sudan"]},
    {"code": "SR", "name": "Суринам", "aliases": ["suriname"]},
    {"code": 'US', "name": "США", "aliases": ["usa", "america", "united states", "united states of america", "сша", "америка", "соединенные штаты", "соединенные штаты америки"]},
    {"code": "SL", "name": "Сьерра-Леоне", "aliases": ["sierra leone"]},
    {"code": "TJ", "name": "Таджикистан", "aliases": ["tajikistan"]},
    {"code": "TH", "name": "Таиланд", "aliases": ["thailand"]},
    {"code": "TW", "name": "Тайвань", "aliases": ["taiwan", "taipei"]},
    {"code": "TZ", "name": "Танзания", "aliases": ["tanzania"]},
    {"code": "TG", "name": "Того", "aliases": ["togo"]},
    {"code": "TK", "name": "Токелау", "aliases": ["tokelau"]},
    {"code": "TO", "name": "Тонга", "aliases": ["tonga"]},
    {"code": "TT", "name": "Тринидад и Тобаго", "aliases": ["trinidad and tobago"]},
    {"code": "TV", "name": "Тувалу", "aliases": ["tuvalu"]},
    {"code": "TN", "name": "Тунис", "aliases": ["tunisia"]},
    {"code": "TM", "name": "Туркменистан", "aliases": ["turkmenistan", "туркмения"]},
    {"code": "TR", "name": "Турция", "aliases": ["turkey"]},
    {"code": "UG", "name": "Уганда", "aliases": ["uganda"]},
    {"code": "UZ", "name": "Узбекистан", "aliases": ["uzbekistan"]},
    {"code": "UY", "name": "Уругвай", "aliases": ["uruguay"]},
    {"code": "FO", "name": "Фарерские острова", "aliases": ["faroe islands"]},
    {"code": "FM", "name": "Федеративные Штаты Микронезии", "aliases": ["federated states of micronesia"]},
    {"code": "FJ", "name": "Фиджи", "aliases": ["fiji"]},
    {"code": "PH", "name": "Филиппины", "aliases": ["philippines"]},
    {"code": "FI", "name": "Финляндия", "aliases": ["finland"]},
    {"code": "FK", "name": "Фолклендские (Мальвинские) острова", "aliases": ["falkland islands (malvinas)"]},
    {"code": "FR", "name": "Франция", "aliases": ["france"]},
    {"code": "GF", "name": "Французская Гвиана", "aliases": ["french guiana"]},
    {"code": "PF", "name": "Французская Полинезия", "aliases": ["french polynesia", "полинезия", "таити"]},
    {"code": "TF", "name": "Французские Южные и Антарктические Территории", "aliases": ["french southern territories"]},
    {"code": "HR", "name": "Хорватия", "aliases": ["croatia"]},
    {"code": "CF", "name": "Центральноафриканская Республика", "aliases": ["central african republic", "central africa", "центральная африка"]},
    {"code": "TD", "name": "Чад", "aliases": ["chad"]},
    {"code": "ME", "name": "Черногория", "aliases": ["montenegro"]},
    {"code": "CZ", "name": "Чехия", "aliases": ["czechia"]},
    {"code": "CL", "name": "Чили", "aliases": ["chile"]},
    {"code": "FM", "name": "Чуук (Трук)", "aliases": ["chuuk"]},
    {"code": "CH", "name": "Швейцария", "aliases": ["switzerland"]},
    {"code": "SE", "name": "Швеция", "aliases": ["sweden"]},
    {"code": "SJ", "name": "Шпицберген и Ян-Майен", "aliases": ["svalbard and jan mayen"]},
    {"code": "LK", "name": "Шри-Ланка", "aliases": ["sri lanka", "шри ланка", "цейлон"]},
    {"code": "EC", "name": "Эквадор", "aliases": ["ecuador"]},
    {"code": "GQ", "name": "Экваториальная Гвинея", "aliases": ["equatorial guinea"]},
    {"code": "ER", "name": "Эритрея", "aliases": ["eritrea"]},
    {"code": "SZ", "name": "Эсватини", "aliases": ["eswatini", "свазиленд"]},
    {"code": "EE", "name": "Эстония", "aliases": ["estonia"]},
    {"code": "ET", "name": "Эфиопия", "aliases": ["ethiopia"]},
    {"code": "ZA", "name": "ЮАР", "aliases": ["republic of south africa", "south africa", "южно-африканская республика", "южная африка"]},
    {"code": "GS", "name": "Южная Георгия и Южные Сандвичевы острова", "aliases": ["south georgia and the south sandwich islands"]},
    {"code": "JM", "name": "Ямайка", "aliases": ["jamaica"]},
    {"code": "FM", "name": "Яп", "aliases": ["yap"]},
    {"code": "JP", "name": "Япония", "aliases": ["japan"]}
]